### ISSUE TITLE
Problem with install on FreePBX Distro

### ISSUE THREAD

**Issue by SolarWind13** [antirek/voicer#23]
Привет.

Есть проблемы с установкой voicer на FreePBX Distro.
Версия дистрибутива - SNG7-PBX-64bit-1904 Release Date: May 2019
```
[root@pbx13 ~]# uname -a
Linux pbx13.local 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@pbx13 ~]# cat /etc/redhat-release
Sangoma Linux release 7.5.1805 (Core)
[root@pbx13 ~]# node -v
v8.11.3
[root@pbx13 ~]# npm -v
5.6.0
```
[root@pbx13 ~]# npm install voicer -g
....skip.....
/usr/bin/voicer -> /usr/lib/node_modules/voicer/app.js
+ voicer@0.1.19
added 114 packages in 13.442s

[root@pbx13 ~]# voicer
bash: /usr/bin/voicer: /usr/bin/nodejs: bad interpreter: No such file or directory

Ок, ладно

[root@pbx13 ~]# ln -s /usr/bin/node /usr/bin/nodejs

Ещё раз:

[root@pbx13 ~]# voicer
no configfile: ./config.js

Ну ладно

[root@pbx13 ~]# export VOICER_CONFIGFILE=/etc/voicer/config

И ещё раз:

```
[root@pbx13 ~]# voicer
/etc/voicer/config.js:4
    },
     ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/voicer/app.js:8:16)
```
Хорошо, добавляем в начало конфига (взят из readme.md) "module.exports ="

[root@pbx13 ~]# voicer
config.js validated successfully! undefined
2019-8-20 16:32:36 - info: server started undefined

О, вроде взлетело.

Заходим на http://pbx_ip:3100
Логинимся с vasya / password - пустило
Пытаюсь прописать 
name - vasya
target - SIP/1001
не получается - при нажатии на кнопки Add / Save ничего не происходит.

Попробовал сделать 
[root@pbx13 ~]# touch /etc/voicer/data/peernames.json
[root@pbx13 ~]# chmod 777 /etc/voicer/data/peernames.json
[root@pbx13 ~]# voicer
config.js validated successfully! undefined
2019-8-20 16:40:19 - info: server started undefined

Не помогло.

Поменял в config.js
          dataFile: 'data/peernames.json'
на
           dataFile: '/etc/voicer/data/peernames.json'
После этого редактирование заработало.

В общем если есть интерес к охвату аудитории использующей FreePBX Distro - эти мелочи неплохо бы или поправить или в документацию перенести.

**Comment by antirek** [comment]
привет, спасибо за детальное описание косяков, есть нюансы установки
хотел бы делать охват аудитории, брал бы деньги за это )) 

а ты не по этому мануалу делал? https://voxlink.ru/kb/asterisk-configuration/golosovoj-nabor-v-asterisk./

**Comment by mifistor** [comment]
Гораздо проще использовать докеризированный образ, где уже есть древняя версия nodejs и всё остальное с пробросом файла конфигурации. Сам я так и делаю, это проще в настройке и не засоряет основную систему, плюс быстро перетаскивается с сервака на сервак )

https://hub.docker.com/r/antirek/voicer

**Comment by antirek** [comment]
Да, Михаил прав, я не очень-то занимаюсь поддержкой, но докер образ жив. Надо хотя бы немного актуализировать voicer, а то над проектом висит vulnerabilities emergency. Вы его тоже видите? 

Михаил, а ты все еще voicer используешь?

**Comment by mifistor** [comment]
Да, использую, причем именно в докер варианте.

**Comment by SolarWind13** [comment]
> привет, спасибо за детальное описание косяков, есть нюансы установки

Завсегда пожалуйста. :-)
Как начну пробовать использовать - тоже отпишусь если что не так.

> хотел бы делать охват аудитории, брал бы деньги за это ))
> 
> а ты не по этому мануалу делал? https://voxlink.ru/kb/asterisk-configuration/golosovoj-nabor-v-asterisk./

На самом деле по трем источникам.
- по ридми 
- по данной ссылке
- по https://habr.com/ru/post/436016/
Пытаюсь скомпилировать из этих источников вариант который у меня заработает.
Сейчас пытаюсь разобраться с запуском через pm2 и изготовлением сервиса.
Пока туго идет - похоже env теряет и не запускается нормально.

**Comment by SolarWind13** [comment]
> 
> 
> Гораздо проще использовать докеризированный образ, где уже есть древняя версия nodejs и всё остальное с пробросом файла конфигурации. Сам я так и делаю, это проще в настройке и не засоряет основную систему, плюс быстро перетаскивается с сервака на сервак )
> 
> https://hub.docker.com/r/antirek/voicer

Спасибо за идею, но...
Во-первых я в докере не очень спец.
Во-вторых налепить на PBX ещё и докер - слегка оверкилл... Особенно с учётом того что нода из коробки там и так есть (на ней User Control Panel и прочие финтифлюхи сделаны)

**Comment by SolarWind13** [comment]
> 
> 
> Да, Михаил прав, я не очень-то занимаюсь поддержкой, но докер образ жив. Надо хотя бы немного актуализировать voicer, а то над проектом висит vulnerabilities emergency. Вы его тоже видите?
> 
> Михаил, а ты все еще voicer используешь?

Ну ежели будет время актуализировать / подправить - было бы замечательно.
